[package]

name = "collabfict"
version = "0.0.1"
authors = [ "Ash Wilson <smashwilson@gmail.com>" ]

[[bin]]

name = "collabfict"

[dependencies]
log = "*"
env_logger = "*"
iron = "*"
router = "*"
persistent = "*"
rand = "*"
hyper = "*"
rustc-serialize = "*"
url = "*"
postgres = "*"
